// Code generated by Kitex v0.10.3. DO NOT EDIT.

package shortlinkservice

import (
	server "github.com/cloudwego/kitex/server"
	short_link "github.com/feifeiz1/rpc/kitex_gen/short_link"
)

// NewInvoker creates a server.Invoker with the given handler and options.
func NewInvoker(handler short_link.ShortLinkService, opts ...server.Option) server.Invoker {
	var options []server.Option

	options = append(options, opts...)

	s := server.NewInvoker(options...)
	if err := s.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	if err := s.Init(); err != nil {
		panic(err)
	}
	return s
}
