// Code generated by Kitex v0.10.3. DO NOT EDIT.

package shortlinkservice

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	short_link "github.com/feifeiz1/rpc/kitex_gen/short_link"
	proto "google.golang.org/protobuf/proto"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"GenLink": kitex.NewMethodInfo(
		genLinkHandler,
		newGenLinkArgs,
		newGenLinkResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
}

var (
	shortLinkServiceServiceInfo                = NewServiceInfo()
	shortLinkServiceServiceInfoForClient       = NewServiceInfoForClient()
	shortLinkServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return shortLinkServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return shortLinkServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return shortLinkServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "ShortLinkService"
	handlerType := (*short_link.ShortLinkService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "proto.short_link",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Protobuf,
		KiteXGenVersion: "v0.10.3",
		Extra:           extra,
	}
	return svcInfo
}

func genLinkHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(short_link.GenLinkReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(short_link.ShortLinkService).GenLink(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *GenLinkArgs:
		success, err := handler.(short_link.ShortLinkService).GenLink(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*GenLinkResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newGenLinkArgs() interface{} {
	return &GenLinkArgs{}
}

func newGenLinkResult() interface{} {
	return &GenLinkResult{}
}

type GenLinkArgs struct {
	Req *short_link.GenLinkReq
}

func (p *GenLinkArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(short_link.GenLinkReq)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *GenLinkArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *GenLinkArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *GenLinkArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *GenLinkArgs) Unmarshal(in []byte) error {
	msg := new(short_link.GenLinkReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var GenLinkArgs_Req_DEFAULT *short_link.GenLinkReq

func (p *GenLinkArgs) GetReq() *short_link.GenLinkReq {
	if !p.IsSetReq() {
		return GenLinkArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *GenLinkArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *GenLinkArgs) GetFirstArgument() interface{} {
	return p.Req
}

type GenLinkResult struct {
	Success *short_link.GenLinkRsp
}

var GenLinkResult_Success_DEFAULT *short_link.GenLinkRsp

func (p *GenLinkResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(short_link.GenLinkRsp)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *GenLinkResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *GenLinkResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *GenLinkResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *GenLinkResult) Unmarshal(in []byte) error {
	msg := new(short_link.GenLinkRsp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *GenLinkResult) GetSuccess() *short_link.GenLinkRsp {
	if !p.IsSetSuccess() {
		return GenLinkResult_Success_DEFAULT
	}
	return p.Success
}

func (p *GenLinkResult) SetSuccess(x interface{}) {
	p.Success = x.(*short_link.GenLinkRsp)
}

func (p *GenLinkResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *GenLinkResult) GetResult() interface{} {
	return p.Success
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) GenLink(ctx context.Context, Req *short_link.GenLinkReq) (r *short_link.GenLinkRsp, err error) {
	var _args GenLinkArgs
	_args.Req = Req
	var _result GenLinkResult
	if err = p.c.Call(ctx, "GenLink", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
